### ISSUE TITLE
empty changelog_text

### ISSUE THREAD

**Issue by pilotak** [heineiuo/create-changelogs#1]
Hi,
i'm trying to generate changelogs for my repo but somehow `steps.changelog.outputs.changelog_text` is always empty. Could you please tell me what am doing wrong? [repo action](https://github.com/pilotak/usb-temp-switch/blob/master/.github/workflows/build.yml) 

Thank you

**Comment by heineiuo** [comment]
@pilotak Sorry for my outdated README. Please try `steps.changelog.outputs.changelogs` instead. 

see: https://github.com/heineiuo/create-changelogs/blob/master/src/actions.js#L16-L18

**Comment by pilotak** [comment]
Thank you, i ammended the actions but the problem now is that all changes are listed since beginning and not in between tags

**Comment by heineiuo** [comment]
@pilotak  Looks like tags were not fetched success, I found a same issue here:  https://github.com/actions/checkout/issues/206

Please try to edit https://github.com/pilotak/usb-temp-switch/blob/master/.github/workflows/build.yml#L28

```diff
- git fetch --prune --unshallow
+ git fetch --prune --unshallow --tags
```

**Comment by pilotak** [comment]
perfect, thanks a lot
